### ISSUE TITLE
为什么下拉刷新 第一次拉完  然后 整个列表 会变成transform: translate3d(0px, -50px, 0px);

### ISSUE THREAD

**Issue by qiansimin88** [mint-ui/mint-ui#32]
这样导致  ul列表的第一行就上去显示不了 而第二次过后再拉  就变成transform: translate3d(0px, 0px, 0px);正常了 请问是什么问题.  还有既然开源  把发布 未经过压缩和混淆的代码么  不然无法根据项目改源代码  这个算是个问题吧

**Comment by mithenji** [comment]
`Child cooking.demo.js:
    
    WARNING in ./example/route.js
    
      ✘  http://eslint.org/docs/rules/no-multi-spaces  Multiple spaces found before 'from'  
      /Users/mithenji/Documents/Github_Code/mint-ui/example/route.js:1:19
      import NavConfig  from './nav.config.json';
                         ^
    
    
    ✘ 1 problem (1 error, 0 warnings)
    
    
    Errors:
      1  http://eslint.org/docs/rules/no-multi-spaces
    Child html-webpack-plugin for "index.html":
        
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
`
demo  跑起来时，报这个错怎么解决呢

**Comment by QingWei-Li** [comment]
@mithenji 代码风格问题

```javascript
```

**Comment by mithenji** [comment]
@QingWei-Li   感谢~，现在运行完美🙂
